name: palmhelp
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # icon
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  phosphor_flutter: ^2.0.1

  # path PDF
  path_provider: ^2.0.13
  path: ^1.8.3

  #urlLuncher
  url_launcher: ^6.1.10

  # splash_screen
  flutter_native_splash: ^2.2.19

  # display pdf
  syncfusion_flutter_pdfviewer: ^20.4.53

  # keep army
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/palm.png"

flutter_native_splash:
  image: assets/logo/palm.png
  color: "#fcfcfc"

flutter:
  uses-material-design: true

  assets:
    - assets/book/
    - assets/book/englais/
    - assets/book/francais/
    - assets/logo/book/